// Importa os tipos e funções necessárias do Next.js e CSS global
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavLinks from "@/app/ui/nav-links";

// Define a fonte Geist Sans como fonte local
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

// Define a fonte Geist Mono como fonte local
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Define os metadados da aplicação
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Componente principal de layout que envolve toda a aplicação
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main>
          <span>Hi, i'm a Layout</span>
          <NavLinks />
          {children}
        </main>
      </body>
    </html>
  );
}